language: php
sudo: false
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
install:
  - composer self-update
  - composer install
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
after_script:
  - php vendor/bin/coveralls -v